server:
  AppVersion: 1.0.0
  Port: :5000
  Mode: Development
  ReadTimeout: 5
  WriteTimeout: 5
  CtxDefaultTimeout: 12
  SSL: false
  Debug: false

logger:
  Development: true
  DisableCaller: false
  DisableStacktrace: false
  Encoding: json
  Level: info

mysql:
  mysqlHost: localhost
  mysqlPort: 3306
  mysqlUsername: root
  mysqlPassword: secret
  mysqlDbName: post_article
  mysqlSslMode: false
  Driver: mysql